### ISSUE TITLE
Modded Ores display

### ISSUE THREAD

**Issue by NesChrome** [AdvancedXRay/XRay-Mod#212]
Hello , i have a bug on your mod ...

**Describe the bug**
Adding modded ore in the menu , then all the ore of the mod are displaying .

**To Reproduce**
1. Install a mod that add ore (thermal foundation that i'm using)
2 . Launch the game with the mod (forge)
3 . Open the x-ray menu add a ore (copper ore from thermal foundation)
4 . Notify that all the ore from thermal foundation are displayed

**Expected behavior**
I expected it could only display the selected ore (copper ore , not only for copper , and also for all the mod that add modded ore)

**Screenshots**
Here the "orange" line are not only copper ore but all the modded ore from the modpack i'm using ...
![x-raybug](https://user-images.githubusercontent.com/105519787/186489420-66061445-dbda-413d-ab2d-16cde47289aa.png)

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: [eg: 1.5.0]
 - FTB Academy (on the ftb app , lastest version 1.4.0

Have a good day (or night) !

**Comment by MichaelHillcox** [comment]
Yeah, this is a state issue, back in 1.12 everyone made their ores 1 block type. This completely fucks over mods like mine. This is fixed in newer versions but due to forge changes, I basically can't load this version of MC in my dev tools, so it's very unlikely this will be fixed. Sorry about that.
