### ISSUE TITLE
Not a bug, but a question of the RenderLevelStageEvent

### ISSUE THREAD

**Issue by gameplayoffert** [AdvancedXRay/XRay-Mod#249]
Hi, i wanted to contact you using your email, but sadly i can't because i don't see your email and instead it's opening a microsoft software. Btw i made a mod and i made an item to search "ores", and it's working good but sadly i want to show it in 3D on the player screen, instead of a position in the chat. I wanted to make that, but it seems to be really complicated so i wanted to know if it was possible to draw a circle in 3D using the RenderLevelStageEvent. I'm asking that to you, because except your mod and the "Journey Map", there is almost no other mods that use this render function and i don't really know who to ask. Otherwise your mod work perfectly fine and is really good :D

**Comment by MichaelHillcox** [comment]
I'm not really sure what you're asking here. All MC rendering is just OpenGL wrapped with their own functions. My code should be a relatively simple example of how to make this work nicely. Rendering a block outline is likely one of the simplest things to do due to Minecraft already doing it for the in-game block cursor highlighter
